# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2010-2016
  project: User Group Management
  version: 1.2
  release: 1.2.1-dev
  latex_documents:
  - - Index
    - mr_usrgrpmgmt.tex
    - User Group Management
    - Xavier Perseguers
    - manual
  latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
...